[world]
name = "zapfc"
description = "ZAP FC on-chain football game"
seed = "zapfc"

[namespace]
default = "dojo_starter"

[env]
rpc_url         = "https://api.cartridge.gg/x/zapfc/katana"
account_address = "0x6677fe62ee39c7b07401f754138502bab7fac99d2d3c5d37df7d1c6fab10819"
private_key     = "0x3e3979c1ed728490308054fe357a9f49cf67f80f9721f44cc57235129e090f4"

[writers]
"dojo_starter-PlayerRegistry" = ["dojo_starter-player_actions","dojo_starter-game_actions","dojo_starter-market_actions"]
"dojo_starter-FormationConfig" = ["dojo_starter-player_actions","dojo_starter-game_actions","dojo_starter-market_actions"]
"dojo_starter-SquadNFT" = ["dojo_starter-player_actions","dojo_starter-market_actions"]
"dojo_starter-GameSession" = ["dojo_starter-game_actions"]
"dojo_starter-VRFRequest" = ["dojo_starter-game_actions"]
"dojo_starter-GlobalCounter" = ["dojo_starter-game_actions","dojo_starter-market_actions"]
"dojo_starter-MarketListing" = ["dojo_starter-market_actions"]
"dojo_starter-PlayerRegistered" = ["dojo_starter-player_actions"]
"dojo_starter-FormationChanged" = ["dojo_starter-player_actions"]
"dojo_starter-StarterEquipped" = ["dojo_starter-player_actions"]
"dojo_starter-CardMinted" = ["dojo_starter-player_actions"]
"dojo_starter-GameStarted" = ["dojo_starter-game_actions"]
"dojo_starter-TurnResolved" = ["dojo_starter-game_actions"]
"dojo_starter-ReadMatchupResolved" = ["dojo_starter-game_actions"]
"dojo_starter-HalftimeReached" = ["dojo_starter-game_actions"]
"dojo_starter-GameFinished" = ["dojo_starter-game_actions"]
"dojo_starter-RewardClaimed" = ["dojo_starter-game_actions"]
"dojo_starter-CardListed" = ["dojo_starter-market_actions"]
"dojo_starter-CardSold" = ["dojo_starter-market_actions"]
"dojo_starter-ListingCancelled" = ["dojo_starter-market_actions"]
"dojo_starter-CardPurchasedFromShop" = ["dojo_starter-market_actions"]
"dojo_starter-CardSoldToShop" = ["dojo_starter-market_actions"]
